export const byDrinkName = {
  drinks: [
    {
      idDrink: '52970',
      strMeal: 'Tunisian Orange Cake',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Tunisian',
      strInstructions: 'Preheat oven to 190 C / Gas 5. Grease a 23cm round springform tin.\r\nCut off the hard bits from the top and bottom of the orange. Slice the orange and remove all seeds. Puree the orange with its peel in a food processor. Add one third of the sugar and the olive oil and continue to mix until well combined.\r\nSieve together flour and baking powder.\r\nBeat the eggs and the remaining sugar with an electric hand mixer for at least five minutes until very fluffy. Fold in half of the flour mixture, then the orange and the vanilla, then fold in the remaining flour. Mix well but not for too long.\r\nPour cake mixture into prepared tin and smooth out. Bake in preheated oven for 20 minutes. Reduce the oven temperature to 160 C / Gas 2 and bake again for 30 minutes Bake until the cake is golden brown and a skewer comes out clean. Cool on a wire cake rack.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/y4jpgq1560459207.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=rCUxg866Ea4',
      strIngredient1: 'Orange',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Flour',
      strIngredient5: 'Baking Powder',
      strIngredient6: 'Eggs',
      strIngredient7: 'Vanilla Extract',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 large',
      strMeasure2: '300g',
      strMeasure3: '75 ml ',
      strMeasure4: '280g',
      strMeasure5: '1 tbs',
      strMeasure6: '4 large',
      strMeasure7: '2 tsp',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/16067/tunisian-orange-cake.aspx',
      dateModified: null,
    },
  ],
};

export const byDrinkFirstLetter = {
  drinks: [
    {
      idMeal: '52768',
      strMeal: 'Apple Frangipan Tart',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/wxywrq1468235067.jpg',
      strTags: 'Tart,Baking,Fruity',
      strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
      strIngredient1: 'digestive biscuits',
      strIngredient2: 'butter',
      strIngredient3: 'Bramley apples',
      strIngredient4: 'butter, softened',
      strIngredient5: 'caster sugar',
      strIngredient6: 'free-range eggs, beaten',
      strIngredient7: 'ground almonds',
      strIngredient8: 'almond extract',
      strIngredient9: 'flaked almonds',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '175g/6oz',
      strMeasure2: '75g/3oz',
      strMeasure3: '200g/7oz',
      strMeasure4: '75g/3oz',
      strMeasure5: '75g/3oz',
      strMeasure6: '2',
      strMeasure7: '75g/3oz',
      strMeasure8: '1 tsp',
      strMeasure9: '50g/1¾oz',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      dateModified: null,
    },
    {
      idMeal: '52893',
      strMeal: 'Apple & Blackberry Crumble',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/xvsurr1511719182.jpg',
      strTags: 'Pudding',
      strYoutube: 'https://www.youtube.com/watch?v=4vhcOwVBDO4',
      strIngredient1: 'Plain Flour',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Butter',
      strIngredient4: 'Braeburn Apples',
      strIngredient5: 'Butter',
      strIngredient6: 'Demerara Sugar',
      strIngredient7: 'Blackberrys',
      strIngredient8: 'Cinnamon',
      strIngredient9: 'Ice Cream',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '120g',
      strMeasure2: '60g',
      strMeasure3: '60g',
      strMeasure4: '300g',
      strMeasure5: '30g',
      strMeasure6: '30g',
      strMeasure7: '120g',
      strMeasure8: '¼ teaspoon',
      strMeasure9: 'to serve',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',
      dateModified: null,
    },
  ],
};

export const byDrinkIngredients = {
  drinks: [
    {
      strMeal: 'Chicken Couscous',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/qxytrx1511304021.jpg',
      idMeal: '52850',
    },
    {
      strMeal: 'Chicken Fajita Mac and Cheese',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/qrqywr1503066605.jpg',
      idMeal: '52818',
    },
    {
      strMeal: 'Chicken Ham and Leek Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/xrrtss1511555269.jpg',
      idMeal: '52875',
    },
    {
      strMeal: 'Chicken Quinoa Greek Salad',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/k29viq1585565980.jpg',
      idMeal: '53011',
    },
    {
      strMeal: 'General Tso\'s Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/1529444113.jpg',
      idMeal: '52951',
    },
    {
      strMeal: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/kvbotn1581012881.jpg',
      idMeal: '52993',
    },
    {
      strMeal: 'Katsu Chicken curry',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/vwrpps1503068729.jpg',
      idMeal: '52820',
    },
    {
      strMeal: 'Rappie Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/drinks/ruwpww1511817242.jpg',
      idMeal: '52933',
    },
  ],
};

export const drinksNull = {
  drinks: [],
};
